name: debug

on:
  check_run:
    types: 
    - created
    - rerequested
    - completed
    - requested_action

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
    - name: Show access token
      run: |
        echo ${{github.sha}}
        echo ${{github.ref}}
      
