on:
  check_suite:
    types: [completed]

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v2
    - run: | 
      echo sha ${{ github.sha }}
      echo ref ${{ github.ref }}
