name: Create check suit

on:
  push:

jobs:
  token:
    runs-on: ubuntu-latest
    env:
      APP_SECRET: ${{ secrets.APP_SECRET}}
      # GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      GH_TOKEN: ${{ secrets.GH_USER_NINO_TOKEN}}
    steps:
    # - uses: actions/checkout@v2
    # - name: generate jwt
    #   id: tokenGenerator
    #   uses: ./.github/actions
    #   with:
    #     installation_id: 23130859
    #     app_secret: ${{ env.APP_SECRET }}
    #     # github_token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Show access token
    #   run: |
    #     echo hello
    #     echo ${{ steps.tokenGenerator.token }}
      
    - name: Create check_suit
      run: |
        gh api -X POST /repos/${{ github.repository }}/check-suites -f head_sha=${{ github.sha }}

    