name: auto-tag

on:
  push:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    env:
      APP_SECRET: ${{ secrets.APP_SECRET}}
    steps:
    - name: prepare jwt payload
      id: jwt_payload
      run: |
        now=$(date +%s)
        exp=$((now+3600))
        echo "::set-output name=iat::$now"
        echo "::set-output exp=exp::$exp"
        echo "::set-output exp=iss::nino"

    - name: Generate token
      id: jwtGenerator
      uses: morzzz007/github-actions-jwt-generator@1.0.1
      with:
        secret: $APP_SECRET
        payload: '{"hello":"world"}'
        # payload: '{"iat": 1644471232, "exp": 1644474832, "iss": client_id" }'

    - name: DUMP Token
      run: |
        echo ${{steps.jwtGenerator.outputs.token}}
    